# General configuration for this scripting library
# Project settings
project_name: mon-key-kit
version: "0.0.1"

# Directory settings
base_dir: "/"
data_dir: "${base_dir}/data"
log_dir: "${base_dir}/logs"
output_dir: "${base_dir}/build"

# Backup settings
backup_enabled: true
backup_interval: 86400  # 24 hours in seconds
backup_retention: 10  # Number of backups to keep

# Performance settings
max_threads: 4
timeout: 300  # Default timeout in seconds

# Feature flags
enable_cloud_integration: false
enable_advanced_analytics: false

# Security
encryption_key: "your-secret-key-here"

# API settings (if applicable)
api_base_url: "https://api.bananas.services"
api_timeout: 10  # API request timeout in seconds

# Database settings (if applicable)
database:
  host: "localhost"
  port: 5432
  name: "devtoolkit_db"
  user: "devtoolkit_user"
  password: "your-database-password"

# Email settings (if applicable)
smtp:
  host: "smtp.example.com"
  port: 587
  user: "notifications@example.com"
  password: "your-smtp-password"
  use_tls: true

# Customization
theme: "default"
language: "en"

# Development settings
debug_mode: false
